### PR TITLE
Introduce gherkin tests.

### PR DESCRIPTION
**Pull request by fabienDaou**

### CODE REVIEW

**Comment by louisdorard** [comment]
What is gherkin? What kind of tests are we introducing and why?

**Comment by louisdorard** [comment]
I see references to "DKU_ANSWERS" environment variables, so I'm guessing that Answers provided inspiration for what we're doing here. Can you share more about the context of this PR?

**Comment by fabienDaou** [comment]
> What is gherkin? What kind of tests are we introducing and why?

[Gherkin](https://cucumber.io/docs/gherkin/reference/) is a specification language meant to facilitate communication between business experts and developers. It is written in natural language. The general use case is to have a business expert and a developer sit together to specify scenarios (what the software should do at a feature level). These scenarios become:
1. documentation of the behavior of the software
2. tests that you can run to detect behavioral regressions

Automating tests for plugins/solutions is a hot topic because the number of Divyia/ds/dev won't scale linearly with the number of plugins. Manual testing is error prone and time consuming, if we dont add test, productivity will hit a plateau. 

So my proposal is to provide a testing library framework for all plugins with existing generic building blocks (see [this repo](https://github.com/dataiku/dss-gherkin-steps), examples folder for example). The end goal is that by just using predefined steps, DS or business experts can write scenarios themselves. These scenarios are then executed as regression tests. And they can do that because this is natural language and not python code.

> I see references to "DKU_ANSWERS" environment variables, so I'm guessing that Answers provided inspiration for what we're doing here. Can you share more about the context of this PR?
It was maybe an old versions, I change the env variable name. But indeed Answers plugin has a full test suite written in gherkin.

**Comment by louisdorard** [comment]
So we would automate https://github.com/dataiku/lca/wiki/Manual-Test-Plan ?

**Comment by fabienDaou** [comment]
Move tests outside visual edit webapp.

**Pull request merged**
